# Generated by Django 5.2.17 on 2026-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('water', 'Water Infrastructure'), ('roads', 'Roads'), ('schools', 'Schools'), ('sanitation', 'Sanitation'), ('electricity', 'Electricity'), ('healthcare', 'Healthcare'), ('other', 'Other')], default='water', max_length=30)),
                ('location', models.CharField(max_length=200)),
                ('language', models.CharField(default='en', max_length=20)),
                ('status', models.CharField(default='submitted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
