# Generated by Django 5.2.17 on 2026-09-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenrequest',
            name='priority_score',
            field=models.IntegerField(default=0),
        ),
    ]
