# Generated by Django 5.2.17 on 2026-09-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_citizenrequest_priority_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenrequest',
            name='affected_population',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizenrequest',
            name='infrastructure_gap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizenrequest',
            name='severity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='citizenrequest',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='citizenrequest',
            name='vulnerability',
            field=models.IntegerField(default=0),
        ),
    ]
