# Generated by Django 5.2.17 on 2026-09-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_citizenrequest_affected_population_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('population', models.IntegerField(default=0)),
                ('households', models.IntegerField(default=0)),
                ('urban_population', models.IntegerField(default=0)),
                ('rural_population', models.IntegerField(default=0)),
                ('literacy_rate', models.FloatField(default=0)),
                ('sc_population', models.IntegerField(default=0)),
                ('st_population', models.IntegerField(default=0)),
            ],
        ),
    ]
