# Generated by Django 5.2.17 on 2026-09-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_districtprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenrequest',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citizen_requests', to='core.districtprofile'),
        ),
    ]
