# Generated by Django 5.2.17 on 2026-09-14 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_citizenrequest_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('indicator', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_indicators', to='core.districtprofile')),
            ],
        ),
    ]
