# Generated by Django 5.2.17 on 2026-09-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_infrastructureindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructureindicator',
            name='data_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infrastructureindicator',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
